# Generated by Django 4.0.6 on 2025-06-05 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=100)),
                ('capacidad_total', models.PositiveIntegerField()),
                ('numero_salas', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('genero', models.CharField(max_length=50)),
                ('duracion', models.PositiveIntegerField(help_text='Duración en minutos')),
                ('fecha_funcion', models.DateField()),
                ('cine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peliculas', to='Funcion.cine')),
            ],
        ),
    ]
