# Generated by Django 4.0.6 on 2025-06-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Funcion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cine',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='cine_logo'),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='peli_archivos'),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='peli_logo'),
        ),
    ]
