# Generated by Django 5.2.1 on 2025-06-05 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Funcion', '0002_cine_logo_pelicula_archivo_pelicula_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pelicula',
            old_name='genero',
            new_name='clasificacion',
        ),
        migrations.RenameField(
            model_name='pelicula',
            old_name='duracion',
            new_name='duracion_min',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='archivo',
        ),
    ]
