# Generated by Django 5.2.1 on 2025-06-05 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Funcion', '0003_rename_genero_pelicula_clasificacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pelicula',
            old_name='logo',
            new_name='imagen',
        ),
    ]
